SAT Solver Template: sat::Variable Class Reference
sat::Variable Class Reference
Structure representing a binary variable in a CNF-SAT problem.
#include <basic_structures.hpp>
Public Member Functions
Variable (unsigned val)
unsigned get () const
bool operator== (Variable other) const
Detailed Description
Structure representing a binary variable in a CNF-SAT problem.
Constructor & Destructor Documentation
Variable()
sat::Variable::Variable (unsigned val)
CTor
Parameters
val variable number (name of the variable)
Member Function Documentation
get()
unsigned sat::Variable::get () const
gets the underlying variable number
Returns
Referenced by sat::operator<<(), sat::operator<<(), and sat::inout::to_dimacs().
operator==()
bool sat::Variable::operator== (Variable other) const
Compares the underlying variable identifier
Returns
True if both variables are the same (have the same identifier)
The documentation for this class was generated from the following files:
Solver/basic_structures.hpp
Solver/basic_structures.cpp