SAT Solver Template: sat Namespace Reference
sat Namespace Reference
Namespaces
concepts
namespace containing various type concepts
detail
inout
Namespace containing dimacs io utilities.
traits
namespace containing various type traits. Prefer using the concepts.
Classes
class Variable
Structure representing a binary variable in a CNF-SAT problem.
class Literal
Structure representing a literal in a CNF-SAT problem.
class Clause
Clause class with watch literals.
struct FirstVariable
Variable selection strategy that selects the first unassigned variable.
class Heuristic
Type erasure heuristic wrapper that can hold any type of heuristic.
class Solver
Main solver class.
struct TimingEvent
Represents an event with a duration.
struct Result
Profiling result.
class Profiler
Profiler that manages multiple events.
class StopWatch
Used to measure time between start a start and a stop event.
class ScopeWatch
Stop watch that automatically adds a timing event to a profiler at destruction.
class RNG
Random number generator singleton class.
Typedefs
using ClausePointer = std::shared_ptr< Clause >
using ConstClausePointer = std::shared_ptr< const Clause >
Enumerations
enum class TruthValue { False = -1 , Undefined = 0 , True = 1 }
Represents a truth value.
Functions
Literal pos (Variable x)
Literal neg (Variable x)
Variable var (Literal l)
std::ostream & operator<< (std::ostream &os, sat::Variable x)
std::ostream & operator<< (std::ostream &os, sat::Literal l)
template<clause_like ClauseT>
std::ostream & operator<< (std::ostream &os, const ClauseT &clause)
Variables
template<typename T >
concept clause_like = concepts::typed_range<T, Literal>
template<typename H >
concept heuristic = concepts::callable_r<H, Variable, const std::vector<TruthValue>, std::size_t>
Detailed Description
Author
Tim Luchterhand
Date
26.11.24
Author
Tim Luchterhand
Date
29.11.24
Author
Tim Luchterhand
Date
27.11.24
Author
Tim Luchterhand
Date
09.08.2024
Enumeration Type Documentation
TruthValue
enum sat::TruthValue strong
Represents a truth value.
Enumerator
False
variable is true
Undefined
variable is unassigned
True
variable is true
Function Documentation
neg()
Literal sat::neg (Variable x)
Creates the negative Literal for a given variable
Parameters
x Variable for which to create the literal
Returns
negative literal of x
Referenced by sat::inout::from_dimacs().
operator<<() [1/3]
template<clause_like ClauseT> std::ostream& sat::operator<< (std::ostream & os, const ClauseT & clause)
Ostream operator allowing for easy printing of clauses
Template Parameters
ClauseT clause type
operator<<() [2/3]
std::ostream & sat::operator<< (std::ostream & os, Literal l)
Ostream operator allowing for easy printing of literals
References sat::Variable::get(), sat::Literal::get(), sat::Literal::sign(), and var().
operator<<() [3/3]
std::ostream & sat::operator<< (std::ostream & os, Variable x)
Ostream operator allowing for easy printing of variables
References sat::Variable::get().
pos()
Literal sat::pos (Variable x)
Creates the positive Literal for a given variable
Parameters
x Variable for which to create the literal
Returns
positive literal of x
Referenced by sat::inout::from_dimacs().
var()
Variable sat::var (Literal l)
Gets the corresponding Variable of a Literal
Parameters
l
Returns
Variable of given Literal
Referenced by operator<<(), and sat::inout::to_dimacs().
Variable Documentation
clause_like
template<typename T > concept sat::clause_like = concepts::typed_range<T, Literal>
Concept modeling a clause. A clause is some range of literals, i.e. it must have accessible members begin() and end() that return an iterator to the first or pas the end elements respectively. For example std::vector<Literal> satisfies this concept.
heuristic
template<typename H > concept sat::heuristic = concepts::callable_r<H, Variable, const std::vector<TruthValue>, std::size_t>
Concept modelling the heuristic interface. A heuristic is a type that can be called with a vector of truth values (the model) and an unsigned integer representing the number of variables that are undecided and returns a sat::Variable