SAT Solver Template: sat::inout Namespace Reference
sat::inout Namespace Reference
Contains functions for reading and writing dimacs format. Also contains printing utilities for basic structures.
Functions
Literal from_dimacs (int val) noexcept
int to_dimacs (Literal l) noexcept
auto read_from_dimacs (std::istream &in) -> std::pair< std::vector< std::vector< Literal >>, std::size_t >
template<std::ranges::range R>
std::string to_dimacs (const R &clauses)
Detailed Description
Contains functions for reading and writing dimacs format. Also contains printing utilities for basic structures.
Author
Tim Luchterhand
Date
27.11.24
Namespace containing dimacs io utilities
Function Documentation
from_dimacs()
Literal sat::inout::from_dimacs (int val) noexcept
Converts an integer to a sat::Literal
Parameters
val literal value. The value +5 for example corresponds to the positive literal of the variable with ID 5, whereas -5 corresponds to the negative literal
Returns
converted Literal
References sat::neg(), and sat::pos().
Referenced by read_from_dimacs().
read_from_dimacs()
auto sat::inout::read_from_dimacs (std::istream & in) -> std::pair< std::vector< std::vector< Literal >>, std::size_t >
Reads a SAT problem from a stream
Parameters
in input stream to read from
Returns
std::pair containing (all clauses of the problem, the number of variables in the problem)
References from_dimacs().
to_dimacs() [1/2]
template<std::ranges::range R> std::string sat::inout::to_dimacs (const R & clauses)
Converts a range of clauses to dimacs format
Template Parameters
R clause range type
Parameters
clauses A range of clauses
Returns
dimacs string
References sat::Variable::get(), and sat::var().
to_dimacs() [2/2]
int sat::inout::to_dimacs (Literal l) noexcept
Converts a sat::Literal to a dimacs literal
Parameters
l Literal to convert
Returns
1 based integer representing the literal in dimacs format
References sat::Variable::get(), sat::Literal::sign(), and sat::var().