SAT Solver Template: sat::ScopeWatch Class Reference
sat::ScopeWatch Class Reference
Stop watch that automatically adds a timing event to a profiler at destruction.
#include <Profiler.hpp>
Public Member Functions
ScopeWatch (Profiler &profiler, std::string eventName)
~ScopeWatch ()
Protected Member Functions
void start ()
TimingEvent getTiming () const
template<typename T >
auto elapsed () const
Protected Attributes
detail::TP startTp
Detailed Description
Stop watch that automatically adds a timing event to a profiler at destruction.
Constructor & Destructor Documentation
ScopeWatch()
sat::ScopeWatch::ScopeWatch (Profiler & profiler, std::string eventName)
CTor. Starts the stop watch
Parameters
profiler profiler where the event is registered
eventName name of the event
References sat::StopWatch::start(), and sat::StopWatch::StopWatch().
~ScopeWatch()
sat::ScopeWatch::~ScopeWatch ()
DTor. Stops the stop watch and adds the event to the scheduler
References sat::Profiler::addEvent(), and sat::StopWatch::getTiming().
Member Function Documentation
elapsed()
template<typename T > auto sat::StopWatch::elapsed () const inline inherited
Get the number of elapsed time units
Template Parameters
T time unit
Returns
number of time units since call to start
getTiming()
TimingEvent sat::StopWatch::getTiming () const inherited
Get the timing event since the last call to start and the time of the call
Returns
TimingEvent with start point set to the last call to start() and end event the current time
Referenced by ~ScopeWatch().
start()
void sat::StopWatch::start () inherited
Resets the start event to the current time
Referenced by ScopeWatch(), and sat::StopWatch::StopWatch().
The documentation for this class was generated from the following files:
Solver/util/Profiler.hpp
Solver/util/Profiler.cpp